export const header = [
    {
        id: 1,
        title: "Asosiy",
        link: "/",
        icon: "bx bxs-dashboard",
        role: "superadmin",
    },
    {
        id: 2,
        title: "Xodimlar",
        link: "/employees",
        icon: "bx bxs-user-rectangle",
        role: 'superadmin',
    },
    {
        id: 3,
        title: "O'quvchilar",
        link: "/students",
        icon: "bx bxs-user",
        role: 'superadmin',
    },
    {
        id: 4,
        title: "Mijozlar",
        link: "/customer",
        icon: "bx bx-body",
        role: 'superadmin',
    },
    {
        id: 5,
        title: "Guruhlar",
        link: "/groups",
        icon: "bx bxs-group",
        role: 'superadmin',
    },
    {
        id: 6,
        title: "Fanlar",
        link: "/subjects",
        icon: "bx bxs-book-bookmark",
        role: 'superadmin',
    },
    {
        id: 7,
        title: "Davomat",
        link: "/attendance",
        icon: "bx bx-user-check",
        role: 'superadmin, staff',
    },
    {
        id: 8,
        title: "To'lovlar",
        link: "/payment",
        icon: "bx bxs-credit-card",
        role: 'superadmin',
    },
    {
        id: 9,
        title: "Testlar",
        link: "/tests",
        icon: "bx bx-credit-card-front",
        role: 'superadmin, staff',
    },
    {
        id: 10,
        title: "Natijalar",
        link: "/results",
        icon: "bx bxs-pie-chart-alt-2",
        role: 'staff, superadmin',
    },
    {
        id: 11,
        title: "Sms",
        link: "/sms",
        icon: "bx bxs-message-rounded-dots",
        role: 'superadmin',
    },
];
